- name: Run package tasks
  ansible.builtin.import_tasks: packages.yml

- name: Run Docker tasks
  ansible.builtin.import_tasks: docker.yml

- name: Run directory tasks
  ansible.builtin.import_tasks: directories.yml

- name: Run config tasks
  ansible.builtin.import_tasks: configs.yml

- name: Run permissions tasks
  ansible.builtin.import_tasks: permissions.yml

- name: Run compose tasks
  ansible.builtin.import_tasks: deploy_stack.yml