- name: Run package tasks
  ansible.builtin.import_tasks: packages.yml

- name: Run Docker tasks
  ansible.builtin.import_tasks: docker.yml

- name: Run directory tasks
  ansible.builtin.import_tasks: directories.yml