monitoring_root: /opt/monitoring

prometheus_host_port: 9091
alertmanager_host_port: 9093
grafana_host_port: 3000
pve_exporter_host_port: 9221

grafana_admin_user: admin
grafana_admin_password: admin

proxmox_nodes:
  - 192.168.45.1
  - 192.168.45.2
  - 192.168.45.3

node_exporter_targets:
  - 192.168.45.1:9100
  - 192.168.45.2:9100
  - 192.168.45.3:9100

ceph_targets:
  - 192.168.45.1:9283
  - 192.168.45.2:9283
  - 192.168.45.3:9283

smartctl_targets:
  - 192.168.45.1:9633
  - 192.168.45.2:9633
  - 192.168.45.3:9633

grafana_dashboards:
  - dashboard_id: 1860
    revision: 37
    datasource: Prometheus
  - dashboard_id: 9550
    revision: 1
    datasource: Prometheus

pve_user: "prometheus@pve"
pve_token_name: "monitoring"
pve_verify_ssl: false